[wokwi]
version = 1
firmware = ".pio/build/esp32-s3-devkitc-1/firmware.bin"
elf = ".pio/build/esp32-s3-devkitc-1/firmware.elf"

rfc2217ServerPort = 4000

[[chip]]
name = "parking-hil"
binary = "parking-hil.chip.wasm"